// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWAFPWOaNyyWHjTc5JEbZR6G115FnLMOA',
    appId: '1:188228784666:web:499fb1487808b8e5e7f7a3',
    messagingSenderId: '188228784666',
    projectId: 'coffee-app-77675',
    authDomain: 'coffee-app-77675.firebaseapp.com',
    storageBucket: 'coffee-app-77675.firebasestorage.app',
    measurementId: 'G-MRHLJX35GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpUCHc5KkPMw9OXFd8GkcYbjXRzzF5Nwc',
    appId: '1:188228784666:android:aeefe2fade075373e7f7a3',
    messagingSenderId: '188228784666',
    projectId: 'coffee-app-77675',
    storageBucket: 'coffee-app-77675.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuyeeG9mD0QWLDU9DJRNgbzdtRkTSOdUo',
    appId: '1:188228784666:ios:ae96762193966a41e7f7a3',
    messagingSenderId: '188228784666',
    projectId: 'coffee-app-77675',
    storageBucket: 'coffee-app-77675.firebasestorage.app',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuyeeG9mD0QWLDU9DJRNgbzdtRkTSOdUo',
    appId: '1:188228784666:ios:ae96762193966a41e7f7a3',
    messagingSenderId: '188228784666',
    projectId: 'coffee-app-77675',
    storageBucket: 'coffee-app-77675.firebasestorage.app',
    iosBundleId: 'com.example.coffeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWAFPWOaNyyWHjTc5JEbZR6G115FnLMOA',
    appId: '1:188228784666:web:231764b99d1831b2e7f7a3',
    messagingSenderId: '188228784666',
    projectId: 'coffee-app-77675',
    authDomain: 'coffee-app-77675.firebaseapp.com',
    storageBucket: 'coffee-app-77675.firebasestorage.app',
    measurementId: 'G-3C2M9MTSHM',
  );
}
